service: plerion-product-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  stage: dev

functions:
  create-product:
    handler: src/functions/products/create.handler
    events:
      - httpApi:
          path: /products
          method: post
  delete-product:
    handler: src/functions/products/delete.handler
    events:
      - httpApi:
          path: /products/{id}
          method: delete
  list-product:
    handler: src/functions/products/list.handler
    events:
      - httpApi:
          path: /products
          method: get
plugins:
  - serverless-plugin-typescript
